apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-platform-oracle-single-node
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rohakbora/AsyncOps-AI.git
    targetRevision: main
    path: k8s/overlays/oracle-single-node
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-task-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
