apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-task-config
  namespace: ai-task-platform
data:
  MONGO_DB_NAME: ai_task_platform
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_QUEUE_KEY: task_jobs
  API_PORT: "5000"
