apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-task-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - redis.yaml
  - backend.yaml
  - worker.yaml
  - frontend.yaml
  - ingress.yaml
images:
  - name: rorabo/ai-task-backend
    newTag: latest
  - name: rorabo/ai-task-worker
    newTag: latest
  - name: rorabo/ai-task-frontend
    newTag: latest
